// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbZ12XkVyMGfn8DHR0BDbROXbZzQQy2J4',
    appId: '1:682114140757:web:e6f01d0d7e8e4f71cb22dc',
    messagingSenderId: '682114140757',
    projectId: 'vtapp-419bd',
    authDomain: 'vtapp-419bd.firebaseapp.com',
    storageBucket: 'vtapp-419bd.firebasestorage.app',
    measurementId: 'G-511JFRH79D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt94jX6V1P3LjqUa8RtgXF0FFhQ2nZoS0',
    appId: '1:682114140757:android:90beed5688b5f549cb22dc',
    messagingSenderId: '682114140757',
    projectId: 'vtapp-419bd',
    storageBucket: 'vtapp-419bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsfAEGuboG93_jW6JP8EwbY6WTFcig4xA',
    appId: '1:682114140757:ios:55a118caf223c501cb22dc',
    messagingSenderId: '682114140757',
    projectId: 'vtapp-419bd',
    storageBucket: 'vtapp-419bd.firebasestorage.app',
    iosBundleId: 'com.example.vtscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsfAEGuboG93_jW6JP8EwbY6WTFcig4xA',
    appId: '1:682114140757:ios:55a118caf223c501cb22dc',
    messagingSenderId: '682114140757',
    projectId: 'vtapp-419bd',
    storageBucket: 'vtapp-419bd.firebasestorage.app',
    iosBundleId: 'com.example.vtscanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbZ12XkVyMGfn8DHR0BDbROXbZzQQy2J4',
    appId: '1:682114140757:web:003d911b45f68987cb22dc',
    messagingSenderId: '682114140757',
    projectId: 'vtapp-419bd',
    authDomain: 'vtapp-419bd.firebaseapp.com',
    storageBucket: 'vtapp-419bd.firebasestorage.app',
    measurementId: 'G-TCM3762H1S',
  );
}
